//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Application.java
//  @ Date : 2018. 11. 24.
//  @ Author : 
//
//




public class Application {
	public void main(String[] args) {
	}
}
