//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Osszeadas.java
//  @ Date : 2018. 11. 24.
//  @ Author : 
//
//




public class Osszeadas {
	public double osszead(double a, double b) {
	}
}
